// Command notices writes THIRD_PARTY_NOTICES.md: the license of every module
// linked into cmd/wazzap (on Windows and Linux), of the Go runtime, and of the
// fonts, icons and data bundled in the source tree. Run it from the repository
// root after changing dependencies or bundled assets:
//
//	go run ./cmd/notices
//
// With -check it writes nothing and fails if the file is out of date (CI).
// go-text must be the patched copy in third_party (patches/apply.sh).
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const out = "THIRD_PARTY_NOTICES.md"

// targets are the systems releases are built for.
var targets = []string{"windows", "linux"}

// bundled lists what the source tree carries from elsewhere, with the
// license files kept beside it.
var bundled = []struct {
	name, source, note string
	files              []string
}{
	{"Noto Color Emoji", "https://github.com/googlefonts/noto-emoji", "font",
		[]string{"internal/ui/fonts/LICENSE-NotoColorEmoji"}},
	{"Anton", "https://github.com/googlefonts/AntonFont", "font, for sticker text",
		[]string{"internal/sticker/fonts/Anton-OFL.txt"}},
	{"Material Symbols", "https://github.com/marella/material-symbols", "icons and wallpaper doodles",
		[]string{"internal/ui/icon/LICENSE-material-symbols"}},
	{"gemoji", "https://github.com/github/gemoji", "emoji names and shortcodes",
		[]string{"internal/ui/LICENSE-gemoji"}},
	{"goldmark-emoji", "https://github.com/yuin/goldmark-emoji", "emoji data, as generated by it",
		[]string{"internal/ui/LICENSE-goldmark-emoji"}},
	{"gioui.org/x/styledtext", "https://git.sr.ht/~eliasnaur/gio-x", "copied and modified",
		[]string{"internal/ui/styledtext/LICENSE"}},
}

// notes says how a module is used, where that matters.
var notes = map[string]string{
	"github.com/go-text/typesetting": "modified by patches/typesetting.patch",
}

type module struct {
	Path, Version, Dir string
	Replace            *module
}

type component struct {
	name, version, source, note string
	files                       map[string]string // file name → text
}

func main() {
	check := flag.Bool("check", false, "fail if "+out+" is out of date instead of writing it")
	flag.Parse()
	log.SetFlags(0)

	var comps []component
	goroot, err := goEnv("GOROOT")
	if err != nil {
		log.Fatal(err)
	}
	comps = append(comps, component{name: "Go standard library and runtime", source: "https://go.dev",
		files: readLicenses(goroot, []string{"LICENSE"})})

	mods, err := modules()
	if err != nil {
		log.Fatal(err)
	}
	for _, m := range mods {
		dir := m.Dir
		if m.Replace != nil {
			dir = m.Replace.Dir
		}
		files := readLicenses(dir, licenseFiles(dir))
		if len(files) == 0 {
			log.Fatalf("%s %s: no license file in %s", m.Path, m.Version, dir)
		}
		comps = append(comps, component{name: m.Path, version: m.Version,
			source: "https://pkg.go.dev/" + m.Path, note: notes[m.Path], files: files})
	}
	for _, b := range bundled {
		files := readLicenses(".", b.files)
		if len(files) != len(b.files) {
			log.Fatalf("%s: missing license file", b.name)
		}
		comps = append(comps, component{name: b.name, source: b.source, note: b.note, files: files})
	}

	text := render(comps)
	if *check {
		old, err := os.ReadFile(out)
		if err != nil || strings.ReplaceAll(string(old), "\r\n", "\n") != text {
			log.Fatalf("%s is out of date: run go run ./cmd/notices", out)
		}
		return
	}
	if err := os.WriteFile(out, []byte(text), 0o644); err != nil {
		log.Fatal(err)
	}
}

func goEnv(name string) (string, error) {
	b, err := exec.Command("go", "env", name).Output()
	return strings.TrimSpace(string(b)), err
}

// modules lists the modules cmd/wazzap links on any of the targets.
func modules() ([]module, error) {
	seen := map[string]module{}
	for _, goos := range targets {
		cmd := exec.Command("go", "list", "-deps", "-json=Standard,Module", "./cmd/wazzap")
		cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH=amd64", "CGO_ENABLED=1")
		cmd.Stderr = os.Stderr
		b, err := cmd.Output()
		if err != nil {
			return nil, fmt.Errorf("go list (%s): %v", goos, err)
		}
		dec := json.NewDecoder(bytes.NewReader(b))
		for {
			var p struct {
				Standard bool
				Module   *module
			}
			if err := dec.Decode(&p); err == io.EOF {
				break
			} else if err != nil {
				return nil, err
			}
			if p.Standard || p.Module == nil || p.Module.Version == "" {
				continue // the standard library, or this module
			}
			seen[p.Module.Path] = *p.Module
		}
	}
	mods := make([]module, 0, len(seen))
	for _, m := range seen {
		mods = append(mods, m)
	}
	sort.Slice(mods, func(i, j int) bool { return mods[i].Path < mods[j].Path })
	return mods, nil
}

var licenseName = regexp.MustCompile(`(?i)^(licen[cs]e|copying|unlicense|notice)`)

func licenseFiles(dir string) []string {
	entries, _ := os.ReadDir(dir)
	var names []string
	for _, e := range entries {
		if !e.IsDir() && licenseName.MatchString(e.Name()) {
			names = append(names, e.Name())
		}
	}
	return names
}

func readLicenses(dir string, names []string) map[string]string {
	files := map[string]string{}
	for _, n := range names {
		b, err := os.ReadFile(filepath.Join(dir, n))
		if err != nil {
			continue
		}
		lines := strings.Split(strings.ReplaceAll(string(b), "\r\n", "\n"), "\n")
		for i, l := range lines {
			lines[i] = strings.TrimRight(l, " \t")
		}
		files[filepath.Base(n)] = strings.Trim(strings.Join(lines, "\n"), "\n")
	}
	return files
}

var spdx = regexp.MustCompile(`SPDX-License-Identifier:\s*(.+)`)

// identify names a license text's license, or returns "".
func identify(text string) string {
	if m := spdx.FindStringSubmatch(text); m != nil {
		return strings.TrimSpace(m[1])
	}
	switch {
	case strings.Contains(text, "Mozilla Public License Version 2.0"):
		return "MPL-2.0"
	case strings.Contains(text, "GNU GENERAL PUBLIC LICENSE") && strings.Contains(text, "Version 3"):
		return "GPL-3.0"
	case strings.Contains(text, "Apache License") && strings.Contains(text, "Version 2.0"):
		return "Apache-2.0"
	case strings.Contains(text, "SIL Open Font License"):
		return "OFL-1.1"
	case strings.Contains(text, "Permission is hereby granted, free of charge"):
		return "MIT"
	case strings.Contains(text, "Permission to use, copy, modify, and") && strings.Contains(text, "with or without fee"):
		return "ISC"
	case strings.Contains(text, "Redistribution and use in source and binary forms"):
		if strings.Contains(text, "Neither the name") || strings.Contains(text, "names of its contributors") {
			return "BSD-3-Clause"
		}
		return "BSD-2-Clause"
	case strings.Contains(strings.ToLower(text), "public domain"):
		return "Public domain"
	}
	return ""
}

func (c component) licenses() string {
	var ids []string
	for _, n := range sortedKeys(c.files) {
		if strings.Contains(strings.ToUpper(n), "3RD-PARTY") {
			continue // a collection of other notices
		}
		if id := identify(c.files[n]); id != "" && !contains(ids, id) {
			ids = append(ids, id)
		}
	}
	return strings.Join(ids, ", ")
}

func render(comps []component) string {
	var b strings.Builder
	b.WriteString(`# Third-party notices

WazzapClients is licensed under the Mozilla Public License 2.0 (see [LICENSE](LICENSE)).
It is built from, and its executables include, the third-party software listed below,
each under its own license, reproduced in full further down.

One of them, libsignal-protocol-go, is licensed under the GNU General Public License
version 3. WazzapClients' own code stays under MPL-2.0, which allows this combination
(MPL-2.0 section 3.3), but **the executables, as a whole, are distributed under the terms
of the GNU GPL version 3**. Their complete source code is at
https://github.com/chomosuke9/wazzapclients, with each release's under its tag.

"WhatsApp" is a trademark of WhatsApp LLC, and "KLIPY" a trademark of its owner. They
are used only to say what this software works with. WazzapClients is not affiliated
with, endorsed by or sponsored by WhatsApp LLC, Meta Platforms, Inc. or KLIPY.

This file is generated by ` + "`go run ./cmd/notices`" + `. Don't edit it by hand.

| Component | Version | License | Notes |
| --- | --- | --- | --- |
`)
	for _, c := range comps {
		fmt.Fprintf(&b, "| [%s](%s) | %s | %s | %s |\n", c.name, c.source, c.version, c.licenses(), c.note)
	}
	for _, c := range comps {
		fmt.Fprintf(&b, "\n## %s", c.name)
		if c.version != "" {
			fmt.Fprintf(&b, " %s", c.version)
		}
		fmt.Fprintf(&b, "\n\n%s\n", c.source)
		for _, n := range sortedKeys(c.files) {
			fmt.Fprintf(&b, "\n### %s\n\n````text\n%s\n````\n", n, c.files[n])
		}
	}
	return b.String()
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func contains(s []string, v string) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}
